title: Bioinformatics Too Indecisive
description: Your site description here
theme: just-the-docs

# For GitHub Pages compatibility
remote_theme: pmarsceill/just-the-docs

# Optional configuration
color_scheme: light
search_enabled: true
