title: Too Indecisive website with just the docs template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://luquelab.github.io/Bioinformatics_Too_Indecisive/

aux_links:
  Template Repository: https://github.com/luquelab/Bioinformatics_Too_Indecisive
